// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pb/v1/sample.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum to represent the result types of the operation.
type ScalarResponse_ResultType int32

const (
	ScalarResponse_RESULT_TYPE_UNSPECIFIED ScalarResponse_ResultType = 0 // Default value, unspecified result type.
	ScalarResponse_RESULT_TYPE_SUCCESS     ScalarResponse_ResultType = 1 // Indicates successful processing.
	ScalarResponse_RESULT_TYPE_ERROR       ScalarResponse_ResultType = 2 // Indicates an error occurred.
)

// Enum value maps for ScalarResponse_ResultType.
var (
	ScalarResponse_ResultType_name = map[int32]string{
		0: "RESULT_TYPE_UNSPECIFIED",
		1: "RESULT_TYPE_SUCCESS",
		2: "RESULT_TYPE_ERROR",
	}
	ScalarResponse_ResultType_value = map[string]int32{
		"RESULT_TYPE_UNSPECIFIED": 0,
		"RESULT_TYPE_SUCCESS":     1,
		"RESULT_TYPE_ERROR":       2,
	}
)

func (x ScalarResponse_ResultType) Enum() *ScalarResponse_ResultType {
	p := new(ScalarResponse_ResultType)
	*p = x
	return p
}

func (x ScalarResponse_ResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalarResponse_ResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_sample_proto_enumTypes[0].Descriptor()
}

func (ScalarResponse_ResultType) Type() protoreflect.EnumType {
	return &file_pb_v1_sample_proto_enumTypes[0]
}

func (x ScalarResponse_ResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalarResponse_ResultType.Descriptor instead.
func (ScalarResponse_ResultType) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_sample_proto_rawDescGZIP(), []int{2, 0}
}

type StreamResponse_ResultType int32

const (
	StreamResponse_RESULT_TYPE_UNSPECIFIED StreamResponse_ResultType = 0
	StreamResponse_RESULT_TYPE_SUCCESS     StreamResponse_ResultType = 1
	StreamResponse_RESULT_TYPE_ERROR       StreamResponse_ResultType = 2
)

// Enum value maps for StreamResponse_ResultType.
var (
	StreamResponse_ResultType_name = map[int32]string{
		0: "RESULT_TYPE_UNSPECIFIED",
		1: "RESULT_TYPE_SUCCESS",
		2: "RESULT_TYPE_ERROR",
	}
	StreamResponse_ResultType_value = map[string]int32{
		"RESULT_TYPE_UNSPECIFIED": 0,
		"RESULT_TYPE_SUCCESS":     1,
		"RESULT_TYPE_ERROR":       2,
	}
)

func (x StreamResponse_ResultType) Enum() *StreamResponse_ResultType {
	p := new(StreamResponse_ResultType)
	*p = x
	return p
}

func (x StreamResponse_ResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamResponse_ResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_sample_proto_enumTypes[1].Descriptor()
}

func (StreamResponse_ResultType) Type() protoreflect.EnumType {
	return &file_pb_v1_sample_proto_enumTypes[1]
}

func (x StreamResponse_ResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamResponse_ResultType.Descriptor instead.
func (StreamResponse_ResultType) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_sample_proto_rawDescGZIP(), []int{4, 0}
}

// Content represents the message content with metadata.
type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the message.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Actual content of the message in binary format.
	Data *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Additional information about the message in key-value pairs.
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_pb_v1_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_pb_v1_sample_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Content) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Content) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ScalarRequest represents the request for a method invocation.
// It includes the content to be sent and a timestamp.
type ScalarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content to be sent in the request.
	Content *Content `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// Timestamp when the message was sent, represented in Unix epoch format.
	Sent          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent,proto3" json:"sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarRequest) Reset() {
	*x = ScalarRequest{}
	mi := &file_pb_v1_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarRequest) ProtoMessage() {}

func (x *ScalarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarRequest.ProtoReflect.Descriptor instead.
func (*ScalarRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_sample_proto_rawDescGZIP(), []int{1}
}

func (x *ScalarRequest) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ScalarRequest) GetSent() *timestamppb.Timestamp {
	if x != nil {
		return x.Sent
	}
	return nil
}

// ScalarResponse represents the server's response to a request.
// It includes details like request ID and processing information.
type ScalarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier correlating to the request.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Total number of messages received in the request.
	MessageCount int64 `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	// Number of messages successfully processed.
	MessagesProcessed int64 `protobuf:"varint,3,opt,name=messages_processed,json=messagesProcessed,proto3" json:"messages_processed,omitempty"`
	// Detailed information or description of the processing result.
	ProcessingDetails string `protobuf:"bytes,4,opt,name=processing_details,json=processingDetails,proto3" json:"processing_details,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScalarResponse) Reset() {
	*x = ScalarResponse{}
	mi := &file_pb_v1_sample_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarResponse) ProtoMessage() {}

func (x *ScalarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_sample_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarResponse.ProtoReflect.Descriptor instead.
func (*ScalarResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_sample_proto_rawDescGZIP(), []int{2}
}

func (x *ScalarResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScalarResponse) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ScalarResponse) GetMessagesProcessed() int64 {
	if x != nil {
		return x.MessagesProcessed
	}
	return 0
}

func (x *ScalarResponse) GetProcessingDetails() string {
	if x != nil {
		return x.ProcessingDetails
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Sent          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent,proto3" json:"sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_pb_v1_sample_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_sample_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_sample_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRequest) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StreamRequest) GetSent() *timestamppb.Timestamp {
	if x != nil {
		return x.Sent
	}
	return nil
}

type StreamResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MessageCount      int64                  `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	MessagesProcessed int64                  `protobuf:"varint,3,opt,name=messages_processed,json=messagesProcessed,proto3" json:"messages_processed,omitempty"`
	ProcessingDetails string                 `protobuf:"bytes,4,opt,name=processing_details,json=processingDetails,proto3" json:"processing_details,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_pb_v1_sample_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_sample_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_sample_proto_rawDescGZIP(), []int{4}
}

func (x *StreamResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamResponse) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *StreamResponse) GetMessagesProcessed() int64 {
	if x != nil {
		return x.MessagesProcessed
	}
	return 0
}

func (x *StreamResponse) GetProcessingDetails() string {
	if x != nil {
		return x.ProcessingDetails
	}
	return ""
}

var File_pb_v1_sample_proto protoreflect.FileDescriptor

const file_pb_v1_sample_proto_rawDesc = "" +
	"\n" +
	"\x12pb/v1/sample.proto\x12\x05pb.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\aContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04data\x128\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1c.pb.v1.Content.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\rScalarRequest\x12(\n" +
	"\acontent\x18\x01 \x01(\v2\x0e.pb.v1.ContentR\acontent\x12.\n" +
	"\x04sent\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04sent\"\x8d\x02\n" +
	"\x0eScalarResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x03R\fmessageCount\x12-\n" +
	"\x12messages_processed\x18\x03 \x01(\x03R\x11messagesProcessed\x12-\n" +
	"\x12processing_details\x18\x04 \x01(\tR\x11processingDetails\"Y\n" +
	"\n" +
	"ResultType\x12\x1b\n" +
	"\x17RESULT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RESULT_TYPE_SUCCESS\x10\x01\x12\x15\n" +
	"\x11RESULT_TYPE_ERROR\x10\x02\"i\n" +
	"\rStreamRequest\x12(\n" +
	"\acontent\x18\x01 \x01(\v2\x0e.pb.v1.ContentR\acontent\x12.\n" +
	"\x04sent\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04sent\"\x8d\x02\n" +
	"\x0eStreamResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x03R\fmessageCount\x12-\n" +
	"\x12messages_processed\x18\x03 \x01(\x03R\x11messagesProcessed\x12-\n" +
	"\x12processing_details\x18\x04 \x01(\tR\x11processingDetails\"Y\n" +
	"\n" +
	"ResultType\x12\x1b\n" +
	"\x17RESULT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RESULT_TYPE_SUCCESS\x10\x01\x12\x15\n" +
	"\x11RESULT_TYPE_ERROR\x10\x022{\n" +
	"\aService\x125\n" +
	"\x06Scalar\x12\x14.pb.v1.ScalarRequest\x1a\x15.pb.v1.ScalarResponse\x129\n" +
	"\x06Stream\x12\x14.pb.v1.StreamRequest\x1a\x15.pb.v1.StreamResponse(\x010\x01B\x8c\x01\n" +
	"\tcom.pb.v1B\vSampleProtoP\x01Z=github.com/rickliujh/kickstart-gogrpc/pkg/api/grpc/pb/v1;pbv1\xa2\x02\x03PXX\xaa\x02\x05Pb.V1\xca\x02\x05Pb\\V1\xe2\x02\x11Pb\\V1\\GPBMetadata\xea\x02\x06Pb::V1b\x06proto3"

var (
	file_pb_v1_sample_proto_rawDescOnce sync.Once
	file_pb_v1_sample_proto_rawDescData []byte
)

func file_pb_v1_sample_proto_rawDescGZIP() []byte {
	file_pb_v1_sample_proto_rawDescOnce.Do(func() {
		file_pb_v1_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_sample_proto_rawDesc), len(file_pb_v1_sample_proto_rawDesc)))
	})
	return file_pb_v1_sample_proto_rawDescData
}

var file_pb_v1_sample_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_v1_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_v1_sample_proto_goTypes = []any{
	(ScalarResponse_ResultType)(0), // 0: pb.v1.ScalarResponse.ResultType
	(StreamResponse_ResultType)(0), // 1: pb.v1.StreamResponse.ResultType
	(*Content)(nil),                // 2: pb.v1.Content
	(*ScalarRequest)(nil),          // 3: pb.v1.ScalarRequest
	(*ScalarResponse)(nil),         // 4: pb.v1.ScalarResponse
	(*StreamRequest)(nil),          // 5: pb.v1.StreamRequest
	(*StreamResponse)(nil),         // 6: pb.v1.StreamResponse
	nil,                            // 7: pb.v1.Content.MetadataEntry
	(*anypb.Any)(nil),              // 8: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_pb_v1_sample_proto_depIdxs = []int32{
	8, // 0: pb.v1.Content.data:type_name -> google.protobuf.Any
	7, // 1: pb.v1.Content.metadata:type_name -> pb.v1.Content.MetadataEntry
	2, // 2: pb.v1.ScalarRequest.content:type_name -> pb.v1.Content
	9, // 3: pb.v1.ScalarRequest.sent:type_name -> google.protobuf.Timestamp
	2, // 4: pb.v1.StreamRequest.content:type_name -> pb.v1.Content
	9, // 5: pb.v1.StreamRequest.sent:type_name -> google.protobuf.Timestamp
	3, // 6: pb.v1.Service.Scalar:input_type -> pb.v1.ScalarRequest
	5, // 7: pb.v1.Service.Stream:input_type -> pb.v1.StreamRequest
	4, // 8: pb.v1.Service.Scalar:output_type -> pb.v1.ScalarResponse
	6, // 9: pb.v1.Service.Stream:output_type -> pb.v1.StreamResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pb_v1_sample_proto_init() }
func file_pb_v1_sample_proto_init() {
	if File_pb_v1_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_sample_proto_rawDesc), len(file_pb_v1_sample_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_v1_sample_proto_goTypes,
		DependencyIndexes: file_pb_v1_sample_proto_depIdxs,
		EnumInfos:         file_pb_v1_sample_proto_enumTypes,
		MessageInfos:      file_pb_v1_sample_proto_msgTypes,
	}.Build()
	File_pb_v1_sample_proto = out.File
	file_pb_v1_sample_proto_goTypes = nil
	file_pb_v1_sample_proto_depIdxs = nil
}
