# Generated by the build-on-aws/terraform-samples/modules/bootstrap-aws-account module.
# While changes won't be overwritten unless run locally and committed, highly recommended
# to not change this outside of the module.
terraform {
  backend "gcs" {
    bucket  = "kickstart-tf-state-alpha"
    prefix  = "terraform/state"
  }

  required_version = ">= 1.12.1"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 6.43.0"
    }
    local = {
      source  = "hashicorp/local"
      version = ">= 2.5.3"
    }
  }
}
